workspace_dir: .
jobs_dir: ./jobs
logs_dir: ./logs
conversion:
  script_path: src/utils/NCandaToTorchGraphDataGUITest.py
  default_args: --inputs {inputs} --labels {labels} --output {output_dir}
training:
  script_path: /isilon/datalake/lcbn_research/final/beach/JonathanP/NeuroGraph/main_NCanda.py
  default_args: --data {dataset_dir} --model {model}
slurm:
  use_slurm_by_default: false
  job_name: MakeTorchGraphData
  output: /isilon/datalake/lcbn_research/final/beach/JonathanP/MakeTorchGraphDataOutput.txt
  error: /isilon/datalake/lcbn_research/final/beach/JonathanP/MakeTorchGraphDataError.txt
  account: ''
  partition: gpu-h100
  qos: ''
  gpus: 2
  mem: 700000M
  time: '4:00:00'
  additional: ''
  env_activation: ''
  cpus: 4
theme: dark colorful
conda_env: NeuroGraph
slurm_conversion: {}
slurm_training: {}
